import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI Mock Interview",
  description: "Generated by create next app",
  icons: {
    icon: "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='16' fill='%23030507'/><circle cx='50' cy='50' r='32' fill='none' stroke='%2300ff88' stroke-width='4' stroke-dasharray='60 140' stroke-dashoffset='0'/><circle cx='50' cy='50' r='32' fill='none' stroke='%2300ff88' stroke-width='4' stroke-dasharray='20 180' stroke-dashoffset='-80'/><text x='50' y='57' text-anchor='middle' font-family='monospace' font-size='22' font-weight='900' fill='%2300ff88'>A</text></svg>",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
